import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import SecondaryBar from "@/components/layout/SecondaryBar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "PONY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[1920px] mx-auto">
        <Navbar />
        <SecondaryBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
